// DO NOT EDIT: generated by adtpp version 1.141210
#include <stdint.h>
#include <stdlib.h>
typedef char *c_string;
#define end_switch() }}}}
#define default() break;}} default: {{
#define else() } else {
#define end_if() }}
#ifndef ADT_MALLOC
#define ADT_MALLOC(s) malloc(s)
#endif
#ifndef ADT_FREE
#define ADT_FREE(s) free(s)
#endif
#ifndef LOW_BIT_USED
#define LOW_BIT_USED 7
#endif
/***************************/
typedef struct _ADT__closure{} *_closure;
#define _closure_T_NUM_CONST (1) 
#define _closure_T_NUM_NONCONST (5) 
#define _closure_constructorNum(v) \
(( _closure_T_NUM_NONCONST>0 && v >= _closure_T_NUM_CONST ?  \
 ( _closure_T_NUM_NONCONST==1 ?  _closure_T_NUM_CONST   : \
(( _closure_T_NUM_NONCONST > (LOW_BIT_USED + 1))  && ((v&LOW_BIT_USED) == (LOW_BIT_USED))  )  ?   \
 (*(int*)((uintptr_t)_ADT_v-LOW_BIT_USED)) + _closure_T_NUM_CONST  : \
((v&(LOW_BIT_USED)) + _closure_T_NUM_CONST)) : v ) )

static __inline void free__closure(_closure v);
#define switch__closure(v) \
{_closure __closure_tchk, _ADT_v=(v); \
int t = _closure_constructorNum((uintptr_t)(_ADT_v)); \
switch(t) {{{


/******************************************************************************/
static __inline void free__closure(_closure v){
	if ((uintptr_t)(v) >= 1){
		ADT_FREE((void*)((uintptr_t)v&~LOW_BIT_USED));
	}
}

;
struct _ADT__closure__cl_delete_this_when_adtpp_fixed {};
#define if__cl_delete_this_when_adtpp_fixed(v) \
{_closure _ADT_v=(v);if (((uintptr_t)(_ADT_v))==0) {
#define else_if__cl_delete_this_when_adtpp_fixed() \
} else if (((uintptr_t)(_ADT_v))==0) {
#define if__cl_delete_this_when_adtpp_fixed_ptr(v) \
{_closure _ADT_v=(v);if (((uintptr_t)(_ADT_v))==0) {
#define case__cl_delete_this_when_adtpp_fixed() \
break;}} case 0: {{_closure _SW_tchk=__closure_tchk;}{char __closure_tchk; 
#define case__cl_delete_this_when_adtpp_fixed_ptr() \
break;}} case 0: {{_closure _SW_tchk=__closure_tchk;}{char __closure_tchk; 

static __inline _closure _cl_delete_this_when_adtpp_fixed(){
	struct _ADT__closure__cl_delete_this_when_adtpp_fixed *v=(struct _ADT__closure__cl_delete_this_when_adtpp_fixed*)0;
	return (_closure)((uintptr_t)v);
}
;
struct _ADT__closure__cl0 {
    _func_ptr f0;
    intptr_t f1;};
#define if__cl0(v, v0, v1) \
{_closure _ADT_v=(v);if ((uintptr_t)(_ADT_v) >= 1 && ((uintptr_t)(_ADT_v)&LOW_BIT_USED)==0) {\
_func_ptr v0=((struct _ADT__closure__cl0*)((uintptr_t)_ADT_v-0))->f0; \
intptr_t v1=((struct _ADT__closure__cl0*)((uintptr_t)_ADT_v-0))->f1; 
#define else_if__cl0(v0, v1) \
} else if ((uintptr_t)(_ADT_v) >= 1 && ((uintptr_t)(_ADT_v)&LOW_BIT_USED)==0)  {\
_func_ptr v0=((struct _ADT__closure__cl0*)((uintptr_t)_ADT_v-0))->f0; \
intptr_t v1=((struct _ADT__closure__cl0*)((uintptr_t)_ADT_v-0))->f1; 
#define if__cl0_ptr(v, v0, v1) \
{_closure _ADT_v=(v);if ((uintptr_t)(_ADT_v) >= 1 && ((uintptr_t)(_ADT_v)&LOW_BIT_USED)==0)  {\
_func_ptr *v0=&((struct _ADT__closure__cl0*)((uintptr_t)_ADT_v-0))->f0; \
intptr_t *v1=&((struct _ADT__closure__cl0*)((uintptr_t)_ADT_v-0))->f1; 
#define case__cl0(v0, v1) \
break;}} case 1: {{_closure _SW_tchk=__closure_tchk;}{char __closure_tchk; \
_func_ptr v0=((struct _ADT__closure__cl0*)((uintptr_t)_ADT_v-0))->f0; \
intptr_t v1=((struct _ADT__closure__cl0*)((uintptr_t)_ADT_v-0))->f1; 
#define case__cl0_ptr(v0, v1) \
break;}} case 1: {{_closure _SW_tchk=__closure_tchk;}{char __closure_tchk; \
_func_ptr *v0=&((struct _ADT__closure__cl0*)((uintptr_t)_ADT_v-0))->f0; \
intptr_t *v1=&((struct _ADT__closure__cl0*)((uintptr_t)_ADT_v-0))->f1; 

static __inline _closure _cl0(_func_ptr v0, intptr_t v1){
	struct _ADT__closure__cl0 *v=(struct _ADT__closure__cl0*)ADT_MALLOC(sizeof(struct _ADT__closure__cl0));
	v->f0=v0; 
	v->f1=v1; 
	return (_closure)(0+(uintptr_t)v);
}
;
struct _ADT__closure__cl1 {
    _func_ptr f0;
    intptr_t f1;
    _void_ptr f2;};
#define if__cl1(v, v0, v1, v2) \
{_closure _ADT_v=(v);if ((uintptr_t)(_ADT_v) >= 1 && ((uintptr_t)(_ADT_v)&LOW_BIT_USED)==1) {\
_func_ptr v0=((struct _ADT__closure__cl1*)((uintptr_t)_ADT_v-1))->f0; \
intptr_t v1=((struct _ADT__closure__cl1*)((uintptr_t)_ADT_v-1))->f1; \
_void_ptr v2=((struct _ADT__closure__cl1*)((uintptr_t)_ADT_v-1))->f2; 
#define else_if__cl1(v0, v1, v2) \
} else if ((uintptr_t)(_ADT_v) >= 1 && ((uintptr_t)(_ADT_v)&LOW_BIT_USED)==1)  {\
_func_ptr v0=((struct _ADT__closure__cl1*)((uintptr_t)_ADT_v-1))->f0; \
intptr_t v1=((struct _ADT__closure__cl1*)((uintptr_t)_ADT_v-1))->f1; \
_void_ptr v2=((struct _ADT__closure__cl1*)((uintptr_t)_ADT_v-1))->f2; 
#define if__cl1_ptr(v, v0, v1, v2) \
{_closure _ADT_v=(v);if ((uintptr_t)(_ADT_v) >= 1 && ((uintptr_t)(_ADT_v)&LOW_BIT_USED)==1)  {\
_func_ptr *v0=&((struct _ADT__closure__cl1*)((uintptr_t)_ADT_v-1))->f0; \
intptr_t *v1=&((struct _ADT__closure__cl1*)((uintptr_t)_ADT_v-1))->f1; \
_void_ptr *v2=&((struct _ADT__closure__cl1*)((uintptr_t)_ADT_v-1))->f2; 
#define case__cl1(v0, v1, v2) \
break;}} case 2: {{_closure _SW_tchk=__closure_tchk;}{char __closure_tchk; \
_func_ptr v0=((struct _ADT__closure__cl1*)((uintptr_t)_ADT_v-1))->f0; \
intptr_t v1=((struct _ADT__closure__cl1*)((uintptr_t)_ADT_v-1))->f1; \
_void_ptr v2=((struct _ADT__closure__cl1*)((uintptr_t)_ADT_v-1))->f2; 
#define case__cl1_ptr(v0, v1, v2) \
break;}} case 2: {{_closure _SW_tchk=__closure_tchk;}{char __closure_tchk; \
_func_ptr *v0=&((struct _ADT__closure__cl1*)((uintptr_t)_ADT_v-1))->f0; \
intptr_t *v1=&((struct _ADT__closure__cl1*)((uintptr_t)_ADT_v-1))->f1; \
_void_ptr *v2=&((struct _ADT__closure__cl1*)((uintptr_t)_ADT_v-1))->f2; 

static __inline _closure _cl1(_func_ptr v0, intptr_t v1, _void_ptr v2){
	struct _ADT__closure__cl1 *v=(struct _ADT__closure__cl1*)ADT_MALLOC(sizeof(struct _ADT__closure__cl1));
	v->f0=v0; 
	v->f1=v1; 
	v->f2=v2; 
	return (_closure)(1+(uintptr_t)v);
}
;
struct _ADT__closure__cl2 {
    _func_ptr f0;
    intptr_t f1;
    _void_ptr f2;
    _void_ptr f3;};
#define if__cl2(v, v0, v1, v2, v3) \
{_closure _ADT_v=(v);if ((uintptr_t)(_ADT_v) >= 1 && ((uintptr_t)(_ADT_v)&LOW_BIT_USED)==2) {\
_func_ptr v0=((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f0; \
intptr_t v1=((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f1; \
_void_ptr v2=((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f2; \
_void_ptr v3=((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f3; 
#define else_if__cl2(v0, v1, v2, v3) \
} else if ((uintptr_t)(_ADT_v) >= 1 && ((uintptr_t)(_ADT_v)&LOW_BIT_USED)==2)  {\
_func_ptr v0=((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f0; \
intptr_t v1=((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f1; \
_void_ptr v2=((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f2; \
_void_ptr v3=((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f3; 
#define if__cl2_ptr(v, v0, v1, v2, v3) \
{_closure _ADT_v=(v);if ((uintptr_t)(_ADT_v) >= 1 && ((uintptr_t)(_ADT_v)&LOW_BIT_USED)==2)  {\
_func_ptr *v0=&((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f0; \
intptr_t *v1=&((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f1; \
_void_ptr *v2=&((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f2; \
_void_ptr *v3=&((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f3; 
#define case__cl2(v0, v1, v2, v3) \
break;}} case 3: {{_closure _SW_tchk=__closure_tchk;}{char __closure_tchk; \
_func_ptr v0=((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f0; \
intptr_t v1=((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f1; \
_void_ptr v2=((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f2; \
_void_ptr v3=((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f3; 
#define case__cl2_ptr(v0, v1, v2, v3) \
break;}} case 3: {{_closure _SW_tchk=__closure_tchk;}{char __closure_tchk; \
_func_ptr *v0=&((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f0; \
intptr_t *v1=&((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f1; \
_void_ptr *v2=&((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f2; \
_void_ptr *v3=&((struct _ADT__closure__cl2*)((uintptr_t)_ADT_v-2))->f3; 

static __inline _closure _cl2(_func_ptr v0, intptr_t v1, _void_ptr v2, _void_ptr v3){
	struct _ADT__closure__cl2 *v=(struct _ADT__closure__cl2*)ADT_MALLOC(sizeof(struct _ADT__closure__cl2));
	v->f0=v0; 
	v->f1=v1; 
	v->f2=v2; 
	v->f3=v3; 
	return (_closure)(2+(uintptr_t)v);
}
;
struct _ADT__closure__cl3 {
    _func_ptr f0;
    intptr_t f1;
    _void_ptr f2;
    _void_ptr f3;
    _void_ptr f4;};
#define if__cl3(v, v0, v1, v2, v3, v4) \
{_closure _ADT_v=(v);if ((uintptr_t)(_ADT_v) >= 1 && ((uintptr_t)(_ADT_v)&LOW_BIT_USED)==3) {\
_func_ptr v0=((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f0; \
intptr_t v1=((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f1; \
_void_ptr v2=((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f2; \
_void_ptr v3=((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f3; \
_void_ptr v4=((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f4; 
#define else_if__cl3(v0, v1, v2, v3, v4) \
} else if ((uintptr_t)(_ADT_v) >= 1 && ((uintptr_t)(_ADT_v)&LOW_BIT_USED)==3)  {\
_func_ptr v0=((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f0; \
intptr_t v1=((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f1; \
_void_ptr v2=((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f2; \
_void_ptr v3=((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f3; \
_void_ptr v4=((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f4; 
#define if__cl3_ptr(v, v0, v1, v2, v3, v4) \
{_closure _ADT_v=(v);if ((uintptr_t)(_ADT_v) >= 1 && ((uintptr_t)(_ADT_v)&LOW_BIT_USED)==3)  {\
_func_ptr *v0=&((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f0; \
intptr_t *v1=&((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f1; \
_void_ptr *v2=&((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f2; \
_void_ptr *v3=&((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f3; \
_void_ptr *v4=&((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f4; 
#define case__cl3(v0, v1, v2, v3, v4) \
break;}} case 4: {{_closure _SW_tchk=__closure_tchk;}{char __closure_tchk; \
_func_ptr v0=((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f0; \
intptr_t v1=((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f1; \
_void_ptr v2=((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f2; \
_void_ptr v3=((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f3; \
_void_ptr v4=((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f4; 
#define case__cl3_ptr(v0, v1, v2, v3, v4) \
break;}} case 4: {{_closure _SW_tchk=__closure_tchk;}{char __closure_tchk; \
_func_ptr *v0=&((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f0; \
intptr_t *v1=&((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f1; \
_void_ptr *v2=&((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f2; \
_void_ptr *v3=&((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f3; \
_void_ptr *v4=&((struct _ADT__closure__cl3*)((uintptr_t)_ADT_v-3))->f4; 

static __inline _closure _cl3(_func_ptr v0, intptr_t v1, _void_ptr v2, _void_ptr v3, _void_ptr v4){
	struct _ADT__closure__cl3 *v=(struct _ADT__closure__cl3*)ADT_MALLOC(sizeof(struct _ADT__closure__cl3));
	v->f0=v0; 
	v->f1=v1; 
	v->f2=v2; 
	v->f3=v3; 
	v->f4=v4; 
	return (_closure)(3+(uintptr_t)v);
}
;
struct _ADT__closure__cl4 {
    _func_ptr f0;
    intptr_t f1;
    _void_ptr f2;
    _void_ptr f3;
    _void_ptr f4;
    _void_ptr f5;};
#define if__cl4(v, v0, v1, v2, v3, v4, v5) \
{_closure _ADT_v=(v);if ((uintptr_t)(_ADT_v) >= 1 && ((uintptr_t)(_ADT_v)&LOW_BIT_USED)==4) {\
_func_ptr v0=((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f0; \
intptr_t v1=((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f1; \
_void_ptr v2=((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f2; \
_void_ptr v3=((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f3; \
_void_ptr v4=((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f4; \
_void_ptr v5=((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f5; 
#define else_if__cl4(v0, v1, v2, v3, v4, v5) \
} else if ((uintptr_t)(_ADT_v) >= 1 && ((uintptr_t)(_ADT_v)&LOW_BIT_USED)==4)  {\
_func_ptr v0=((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f0; \
intptr_t v1=((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f1; \
_void_ptr v2=((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f2; \
_void_ptr v3=((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f3; \
_void_ptr v4=((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f4; \
_void_ptr v5=((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f5; 
#define if__cl4_ptr(v, v0, v1, v2, v3, v4, v5) \
{_closure _ADT_v=(v);if ((uintptr_t)(_ADT_v) >= 1 && ((uintptr_t)(_ADT_v)&LOW_BIT_USED)==4)  {\
_func_ptr *v0=&((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f0; \
intptr_t *v1=&((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f1; \
_void_ptr *v2=&((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f2; \
_void_ptr *v3=&((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f3; \
_void_ptr *v4=&((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f4; \
_void_ptr *v5=&((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f5; 
#define case__cl4(v0, v1, v2, v3, v4, v5) \
break;}} case 5: {{_closure _SW_tchk=__closure_tchk;}{char __closure_tchk; \
_func_ptr v0=((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f0; \
intptr_t v1=((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f1; \
_void_ptr v2=((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f2; \
_void_ptr v3=((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f3; \
_void_ptr v4=((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f4; \
_void_ptr v5=((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f5; 
#define case__cl4_ptr(v0, v1, v2, v3, v4, v5) \
break;}} case 5: {{_closure _SW_tchk=__closure_tchk;}{char __closure_tchk; \
_func_ptr *v0=&((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f0; \
intptr_t *v1=&((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f1; \
_void_ptr *v2=&((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f2; \
_void_ptr *v3=&((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f3; \
_void_ptr *v4=&((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f4; \
_void_ptr *v5=&((struct _ADT__closure__cl4*)((uintptr_t)_ADT_v-4))->f5; 

static __inline _closure _cl4(_func_ptr v0, intptr_t v1, _void_ptr v2, _void_ptr v3, _void_ptr v4, _void_ptr v5){
	struct _ADT__closure__cl4 *v=(struct _ADT__closure__cl4*)ADT_MALLOC(sizeof(struct _ADT__closure__cl4));
	v->f0=v0; 
	v->f1=v1; 
	v->f2=v2; 
	v->f3=v3; 
	v->f4=v4; 
	v->f5=v5; 
	return (_closure)(4+(uintptr_t)v);
}
